In [69]:
from google.colab import files
uploaded = files.upload()

Saving Dataset 1_origin.csv to Dataset 1_origin.csv

In [166]:
import pandas as pd
import numpy as np

df = pd.read_csv("Dataset 1_origin.csv")
df.sample(20)

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
1777,164,1977,PhD,Married,28973.0,0,0,13-10-2012,59,206,...,8,0,0,0,0,0,0,3,11,0
425,7284,1953,Graduation,Married,48686.0,1,2,04-12-2013,8,10,...,8,0,0,0,0,0,0,3,11,0
1759,5883,1972,Graduation,Married,77981.0,1,0,26-05-2013,78,138,...,5,0,0,0,0,0,0,3,11,0
2046,4268,1959,Graduation,Married,53154.0,0,1,09-06-2014,50,129,...,4,0,0,0,0,0,0,3,11,0
305,9274,1961,Master,Married,80950.0,0,0,28-03-2013,44,525,...,2,0,0,0,1,0,0,3,11,0
1626,8041,1971,PhD,Widow,47111.0,0,1,08-09-2012,35,595,...,9,0,0,0,0,0,0,3,11,0
1770,5093,1974,PhD,Divorced,25509.0,1,0,18-09-2012,15,40,...,9,0,0,0,0,0,0,3,11,1
1936,4827,1956,PhD,Single,54998.0,0,1,10-03-2013,3,154,...,4,0,0,0,0,0,0,3,11,1
2071,2712,1956,Graduation,Married,71866.0,0,1,25-12-2013,85,184,...,3,0,0,0,0,0,0,3,11,0
1910,5832,1960,2n Cycle,Together,92556.0,0,0,20-04-2014,32,493,...,0,0,0,0,0,0,0,3,11,0
988,9305,1976,2n Cycle,Single,79689.0,0,0,12-05-2013,65,311,...,2,0,0,0,0,0,0,3,11,0
1201,9500,1959,Graduation,Married,58113.0,0,1,25-01-2013,66,221,...,7,0,0,0,0,0,1,3,11,0
2014,3262,1958,Graduation,Single,68281.0,0,0,07-08-2012,31,995,...,5,0,0,0,0,0,0,3,11,1
42,8430,1957,Graduation,Together,21994.0,0,1,24-12-2012,4,9,...,5,0,0,0,0,0,0,3,11,0
1149,10525,1986,Graduation,Single,26576.0,1,0,13-10-2012,40,10,...,9,1,0,0,0,0,0,3,11,1
204,1030,1965,PhD,Single,40637.0,1,1,17-07-2013,72,22,...,7,0,0,0,0,0,0,3,11,0
1003,5527,1987,Graduation,Together,22434.0,1,0,13-02-2013,25,4,...,8,0,0,0,0,0,0,3,11,0
604,1177,1966,Master,Together,49618.0,1,1,26-01-2013,77,80,...,7,0,0,0,0,0,0,3,11,0
2109,3104,1961,Graduation,Single,82332.0,0,0,17-09-2012,89,830,...,2,0,0,1,0,0,0,3,11,1
777,4964,1958,PhD,Together,74250.0,0,0,26-01-2014,90,680,...,1,0,0,0,0,0,0,3,11,0

In [167]:
df = df.loc[: , 'Education':'Kidhome']
df = df.drop('Income',axis=1)

In [76]:
df

       Education Marital_Status  Kidhome
0     Graduation         Single        0
1     Graduation         Single        1
2     Graduation       Together        0
3     Graduation       Together        1
4            PhD        Married        1
...          ...            ...      ...
2235  Graduation        Married        0
2236         PhD       Together        2
2237  Graduation       Divorced        0
2238      Master       Together        0
2239         PhD        Married        1

[2240 rows x 3 columns]

In [168]:
df["Marital_Status"].value_counts()

Marital_Status
Married     864
Together    580
Single      480
Divorced    232
Widow        77
Alone         3
Absurd        2
YOLO          2
Name: count, dtype: int64

In [169]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(df.drop("Kidhome", axis=1), df["Kidhome"], test_size=0.25 , random_state=0)

In [173]:
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder(categories=[["PhD","Master","Graduation","2n Cycle","Basic"],["Married","Together","Divorced","Widow","Single","Alone","Absurd","YOLO"]])

In [174]:
oe.fit(x_train)

OrdinalEncoder(categories=[['PhD', 'Master', 'Graduation', '2n Cycle', 'Basic'],
                           ['Married', 'Together', 'Divorced', 'Widow',
                            'Single', 'Alone', 'Absurd', 'YOLO']])

In [175]:
x_train = oe.transform(x_train)
x_test = oe.transform(x_test)

In [180]:
x_train

array([[2., 1.],
       [2., 2.],
       [2., 0.],
       ...,
       [0., 4.],
       [2., 0.],
       [2., 1.]])

In [151]:
oe.categories_

[array(['PhD', 'Master', 'Graduation', '2n Cycle', 'Basic'], dtype=object),
 array(['Married', 'Together', 'Divorced', 'Widow', 'Single', 'Alone',
        'Absurd', 'YOLO'], dtype=object)]

In [131]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
le.fit(y_train)

LabelEncoder()

In [132]:
le.classes_

array([0, 1, 2])

In [133]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [134]:
y_train

array([0, 0, 1, ..., 1, 0, 0])

In [135]:
y_test

array([0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 2, 1, 0, 1, 0, 1, 0, 2, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 2, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 2, 1, 0, 1, 2, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 2, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 2, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 2, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 2, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 2,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 2])