In [2]:
from google.colab import files
uploaded = files.upload()

Saving hr_practice_dataset.csv to hr_practice_dataset (1).csv

In [27]:
import pandas as pd

df = pd.read_csv("hr_practice_dataset.csv")
df

,Emp_ID,Emp_Name,Department,JobTitle,Salary,Gender,EmploymentStatus,PerformanceScore,RecruitmentSource
0,1001,Alice Brown,Production,Production Technician I,42000,F,Active,Fully Meets,Indeed
1,1002,Bob Smith,IT/IS,Data Analyst,68000,M,Active,Exceeds,LinkedIn
2,1003,Carol Jones,Sales,Sales Manager,75000,F,Active,Fully Meets,Indeed
3,1004,David Miller,Production,Production Technician II,48000,M,Voluntarily Terminated,Fully Meets,Google Search
4,1005,Eva Wilson,IT/IS,Software Engineer,92000,F,Active,Exceeds,Employee Referral
5,1006,Frank Taylor,Production,Production Technician I,41000,M,Active,Needs Improvement,Indeed
6,1007,Grace Thomas,Admin Offices,Administrative Assistant,39000,F,Active,Fully Meets,Website
7,1008,Henry Moore,IT/IS,Network Engineer,88000,M,Active,Fully Meets,LinkedIn
8,1009,Ivy Martin,Sales,Area Sales Manager,72000,F,Active,Fully Meets,CareerBuilder
9,1010,Jack Lee,Production,Production Technician I,43000,M,Terminated for Cause,PIP,Indeed
10,1011,Kathy Clark,IT/IS,BI Developer,81000,F,Active,Exceeds,LinkedIn
11,1012,Leo Walker,Production,Production Technician II,51000,M,Active,Fully Meets,Google Search
12,1013,Mona Hall,Sales,Sales Manager,79000,F,Voluntarily Terminated,Fully Meets,Indeed
13,1014,Nick Allen,Production,Production Technician I,40000,M,Active,Needs Improvement,Website
14,1015,Olivia Young,IT/IS,Data Architect,110000,F,Active,Exceeds,Employee Referral
15,1016,Paul Hernandez,Admin Offices,Accountant I,56000,M,Active,Fully Meets,Indeed
16,1017,Queen Patel,Production,Production Technician I,44500,F,Active,Fully Meets,LinkedIn
17,1018,Ryan Scott,IT/IS,IT Manager,98000,M,Active,Fully Meets,LinkedIn
18,1019,Sara King,Sales,Sales Executive,61000,F,Active,Fully Meets,Indeed
19,1020,Tom Baker,Production,Production Technician II,52000,M,Active,Exceeds,Employee Referral

In [4]:
df.head()
df.tail()

,Emp_ID,Emp_Name,Department,JobTitle,Salary,Gender,EmploymentStatus,PerformanceScore,RecruitmentSource
15,1016,Paul Hernandez,Admin Offices,Accountant I,56000,M,Active,Fully Meets,Indeed
16,1017,Queen Patel,Production,Production Technician I,44500,F,Active,Fully Meets,LinkedIn
17,1018,Ryan Scott,IT/IS,IT Manager,98000,M,Active,Fully Meets,LinkedIn
18,1019,Sara King,Sales,Sales Executive,61000,F,Active,Fully Meets,Indeed
19,1020,Tom Baker,Production,Production Technician II,52000,M,Active,Exceeds,Employee Referral

In [6]:
df.shape

(20, 9)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Emp_ID             20 non-null     int64
 1   Emp_Name           20 non-null     object
 2   Department         20 non-null     object
 3   JobTitle           20 non-null     object
 4   Salary             20 non-null     int64
 5   Gender             20 non-null     object
 6   EmploymentStatus   20 non-null     object
 7   PerformanceScore   20 non-null     object
 8   RecruitmentSource  20 non-null     object
dtypes: int64(2), object(7)
memory usage: 1.5+ KB

In [9]:
df.isnull().sum()

Emp_ID               0
Emp_Name             0
Department           0
JobTitle             0
Salary               0
Gender               0
EmploymentStatus     0
PerformanceScore     0
RecruitmentSource    0
dtype: int64

In [10]:
df["Department"].nunique()

4

In [11]:
df["Department"].unique()

array(['Production', 'IT/IS', 'Sales', 'Admin Offices'], dtype=object)

In [12]:
df['Emp_Name'].count()

np.int64(20)

In [31]:
df[df["Salary"] > 70000]

,Emp_ID,Emp_Name,Department,JobTitle,Salary,Gender,EmploymentStatus,PerformanceScore,RecruitmentSource
2,1003,Carol Jones,Sales,Sales Manager,75000,F,Active,Fully Meets,Indeed
4,1005,Eva Wilson,IT/IS,Software Engineer,92000,F,Active,Exceeds,Employee Referral
7,1008,Henry Moore,IT/IS,Network Engineer,88000,M,Active,Fully Meets,LinkedIn
8,1009,Ivy Martin,Sales,Area Sales Manager,72000,F,Active,Fully Meets,CareerBuilder
10,1011,Kathy Clark,IT/IS,BI Developer,81000,F,Active,Exceeds,LinkedIn
12,1013,Mona Hall,Sales,Sales Manager,79000,F,Voluntarily Terminated,Fully Meets,Indeed
14,1015,Olivia Young,IT/IS,Data Architect,110000,F,Active,Exceeds,Employee Referral
17,1018,Ryan Scott,IT/IS,IT Manager,98000,M,Active,Fully Meets,LinkedIn

In [36]:
df.groupby("Gender").count()

,Emp_ID,Emp_Name,Department,JobTitle,Salary,EmploymentStatus,PerformanceScore,RecruitmentSource
Gender,,,,,,,,
F,10,10,10,10,10,10,10,10
M,10,10,10,10,10,10,10,10

In [38]:
df["Department"].value_counts()

Department
Production       8
IT/IS            6
Sales            4
Admin Offices    2
Name: count, dtype: int64

In [46]:
df.groupby("Department")["Salary"].mean()

Department
Admin Offices    47500.0
IT/IS            89500.0
Production       45187.5
Sales            71750.0
Name: Salary, dtype: float64

In [48]:
df.groupby("Department")["Salary"].mean().sort_values(ascending = False).head(1)

Department
IT/IS    89500.0
Name: Salary, dtype: float64

In [51]:
df["Salary"].min() , df["Salary"].max()

(39000, 110000)

In [59]:
df.sort_values(by="Salary", ascending=False)[
    ["Emp_ID", "Emp_Name", "Department", "Salary"]
].head(5)

    Emp_ID      Emp_Name Department  Salary
14    1015  Olivia Young      IT/IS  110000
17    1018    Ryan Scott      IT/IS   98000
4     1005    Eva Wilson      IT/IS   92000
7     1008   Henry Moore      IT/IS   88000
10    1011   Kathy Clark      IT/IS   81000

In [60]:
df["EmploymentStatus"].value_counts()

EmploymentStatus
Active                    17
Voluntarily Terminated     2
Terminated for Cause       1
Name: count, dtype: int64

In [ ]:
#df.groupby("Year")["Emp_Name"].count()

In [63]:
df[df["PerformanceScore"] == "Exceeds"]

,Emp_ID,Emp_Name,Department,JobTitle,Salary,Gender,EmploymentStatus,PerformanceScore,RecruitmentSource
1,1002,Bob Smith,IT/IS,Data Analyst,68000,M,Active,Exceeds,LinkedIn
4,1005,Eva Wilson,IT/IS,Software Engineer,92000,F,Active,Exceeds,Employee Referral
10,1011,Kathy Clark,IT/IS,BI Developer,81000,F,Active,Exceeds,LinkedIn
14,1015,Olivia Young,IT/IS,Data Architect,110000,F,Active,Exceeds,Employee Referral
19,1020,Tom Baker,Production,Production Technician II,52000,M,Active,Exceeds,Employee Referral

In [67]:
df[df["Salary"] > df.groupby("Department")["Salary"].transform("mean")]

,Emp_ID,Emp_Name,Department,JobTitle,Salary,Gender,EmploymentStatus,PerformanceScore,RecruitmentSource
2,1003,Carol Jones,Sales,Sales Manager,75000,F,Active,Fully Meets,Indeed
3,1004,David Miller,Production,Production Technician II,48000,M,Voluntarily Terminated,Fully Meets,Google Search
4,1005,Eva Wilson,IT/IS,Software Engineer,92000,F,Active,Exceeds,Employee Referral
8,1009,Ivy Martin,Sales,Area Sales Manager,72000,F,Active,Fully Meets,CareerBuilder
11,1012,Leo Walker,Production,Production Technician II,51000,M,Active,Fully Meets,Google Search
12,1013,Mona Hall,Sales,Sales Manager,79000,F,Voluntarily Terminated,Fully Meets,Indeed
14,1015,Olivia Young,IT/IS,Data Architect,110000,F,Active,Exceeds,Employee Referral
15,1016,Paul Hernandez,Admin Offices,Accountant I,56000,M,Active,Fully Meets,Indeed
17,1018,Ryan Scott,IT/IS,IT Manager,98000,M,Active,Fully Meets,LinkedIn
19,1020,Tom Baker,Production,Production Technician II,52000,M,Active,Exceeds,Employee Referral