In [1]:
from google.colab import files
uploaded = files.upload()

Saving titanic_practice_dataset.csv to titanic_practice_dataset.csv

In [132]:
import pandas as pd
df =pd.read_csv("titanic_practice_dataset.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,Passenger_1,male,22.6,3,1,TKT1000,242.58,B28,S
1,2,1,1,Passenger_2,female,18.9,4,3,TKT1001,222.11,NaN,C
2,3,1,1,Passenger_3,male,28.5,0,3,TKT1002,232.66,NaN,S
3,4,0,3,Passenger_4,female,15.5,0,2,TKT1003,248.78,C85,S
4,5,0,3,Passenger_5,male,22.2,4,3,TKT1004,51.73,B28,S
...,...,...,...,...,...,...,...,...,...,...,...,...
195,196,0,3,Passenger_196,male,39.7,0,3,TKT1195,50.20,NaN,C
196,197,1,3,Passenger_197,female,55.9,1,1,TKT1196,35.10,NaN,C
197,198,1,2,Passenger_198,male,45.8,0,0,TKT1197,162.74,NaN,S
198,199,1,3,Passenger_199,male,26.2,0,0,TKT1198,179.55,E46,S
199,200,1,3,Passenger_200,male,14.5,3,1,TKT1199,17.58,NaN,S

In [3]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,Passenger_1,male,22.6,3,1,TKT1000,242.58,B28,S
1,2,1,1,Passenger_2,female,18.9,4,3,TKT1001,222.11,NaN,C
2,3,1,1,Passenger_3,male,28.5,0,3,TKT1002,232.66,NaN,S
3,4,0,3,Passenger_4,female,15.5,0,2,TKT1003,248.78,C85,S
4,5,0,3,Passenger_5,male,22.2,4,3,TKT1004,51.73,B28,S
5,6,0,1,Passenger_6,female,13.2,2,2,TKT1005,105.10,C85,S
6,7,0,1,Passenger_7,male,57.5,2,0,TKT1006,191.98,E46,S
7,8,1,3,Passenger_8,male,30.5,2,0,TKT1007,177.04,NaN,S
8,9,0,1,Passenger_9,female,20.2,4,2,TKT1008,46.94,E46,S
9,10,1,1,Passenger_10,male,33.0,0,0,TKT1009,205.80,NaN,S

In [4]:
df.shape

(200, 12)

In [14]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          137
Embarked         0
dtype: int64

In [21]:
df[df["Survived"] == 1].shape

(74, 12)

In [23]:
df["Age"].mean()

np.float64(29.9505)

In [43]:
df.groupby("Sex").count()

Sex     PassengerId  Survived  Pclass  Name           Age   SibSp  Parch  Ticket   Fare    Cabin  Embarked
female  4            0         3       Passenger_4    15.5  0      2      TKT1003  248.78  C85    S           1
        6            0         1       Passenger_6    13.2  2      2      TKT1005  105.10  C85    S           1
        9            0         1       Passenger_9    20.2  4      2      TKT1008  46.94   E46    S           1
        13           1         3       Passenger_13   38.6  2      1      TKT1012  138.87  E46    C           1
        22           0         3       Passenger_22   26.5  2      0      TKT1021  216.91  B28    S           1
                                                                                                             ..
male    168          0         3       Passenger_168  36.6  1      3      TKT1167  154.00  B28    C           1
        171          1         1       Passenger_171  52.3  0      0      TKT1170  216.43  C85    S           1
        177          1         3       Passenger_177  6.3   2      2      TKT1176  246.80  C85    S           1
        180          0         2       Passenger_180  24.0  2      0      TKT1179  158.36  E46    S           1
        199          1         3       Passenger_199  26.2  0      0      TKT1198  179.55  E46    S           1
Name: count, Length: 63, dtype: int64

In [51]:
df["Survived"].mean()*100

np.float64(37.0)

In [53]:
df.groupby("Pclass")["Fare"].count()

Pclass
1     47
2     38
3    115
Name: Fare, dtype: int64

In [54]:
df.groupby("Sex")["Survived"].count()

Sex
female     73
male      127
Name: Survived, dtype: int64

In [55]:
df.groupby("Pclass")["Survived"].count()

Pclass
1     47
2     38
3    115
Name: Survived, dtype: int64

In [58]:
df["Age"].sort_values(ascending=False).head(1) , df["Age"].sort_values(ascending=True).head(1)

(121    78.0
 Name: Age, dtype: float64,
 112    1.5
 Name: Age, dtype: float64)

In [60]:
df[df["Fare"] > 100 ]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,Passenger_1,male,22.6,3,1,TKT1000,242.58,B28,S
1,2,1,1,Passenger_2,female,18.9,4,3,TKT1001,222.11,NaN,C
2,3,1,1,Passenger_3,male,28.5,0,3,TKT1002,232.66,NaN,S
3,4,0,3,Passenger_4,female,15.5,0,2,TKT1003,248.78,C85,S
5,6,0,1,Passenger_6,female,13.2,2,2,TKT1005,105.10,C85,S
...,...,...,...,...,...,...,...,...,...,...,...,...
191,192,1,2,Passenger_192,male,26.2,2,0,TKT1191,146.21,NaN,S
192,193,1,2,Passenger_193,male,20.0,2,0,TKT1192,175.47,NaN,C
193,194,1,3,Passenger_194,male,29.2,0,1,TKT1193,202.14,NaN,S
197,198,1,2,Passenger_198,male,45.8,0,0,TKT1197,162.74,NaN,S
198,199,1,3,Passenger_199,male,26.2,0,0,TKT1198,179.55,E46,S

In [61]:
df.groupby("Embarked")["PassengerId"].count()

Embarked
C     40
Q     18
S    142
Name: PassengerId, dtype: int64

In [71]:
df.groupby('Survived')['Age'].mean().rename({
    0: "Not Survived",
    1: "Survived"
})

Survived
0    29.996032
1    29.872973
Name: Age, dtype: float64

In [118]:
df["Parents"] = df["SibSp"] + df["Parch"]
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Parents
0,1,0,3,Passenger_1,male,22.6,3,1,TKT1000,242.58,B28,S,4
1,2,1,1,Passenger_2,female,18.9,4,3,TKT1001,222.11,NaN,C,7
2,3,1,1,Passenger_3,male,28.5,0,3,TKT1002,232.66,NaN,S,3
3,4,0,3,Passenger_4,female,15.5,0,2,TKT1003,248.78,C85,S,2
4,5,0,3,Passenger_5,male,22.2,4,3,TKT1004,51.73,B28,S,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,196,0,3,Passenger_196,male,39.7,0,3,TKT1195,50.20,NaN,C,3
196,197,1,3,Passenger_197,female,55.9,1,1,TKT1196,35.10,NaN,C,2
197,198,1,2,Passenger_198,male,45.8,0,0,TKT1197,162.74,NaN,S,0
198,199,1,3,Passenger_199,male,26.2,0,0,TKT1198,179.55,E46,S,0
199,200,1,3,Passenger_200,male,14.5,3,1,TKT1199,17.58,NaN,S,4

In [79]:
df.groupby("Parents")["Survived"].mean().sort_values(ascending=False).head(1)

Parents
2    0.486486
Name: Survived, dtype: float64

In [86]:
df['FareGroup'] = pd.cut(df['Fare'],
                         bins=[0, 25, 50, 100, 250],
                         labels=['Low', 'Medium', 'High', 'Very High'])

df.groupby('FareGroup')['Survived'].mean() * 100

/tmp/ipykernel_186/226202767.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('FareGroup')['Survived'].mean() * 100

FareGroup
Low          33.333333
Medium       39.285714
High         42.424242
Very High    35.433071
Name: Survived, dtype: float64

In [91]:
df.groupby("Pclass")["Survived"].mean()

Pclass
1    0.319149
2    0.394737
3    0.382609
Name: Survived, dtype: float64

In [92]:
df.groupby("Pclass")["Survived"].agg(
    SurvivalRate="mean",
    PassengerCount="count"
).sort_values(by="SurvivalRate", ascending=False)

        SurvivalRate  PassengerCount
Pclass
2           0.394737              38
3           0.382609             115
1           0.319149              47

In [111]:
df['AgeGroup'] = pd.cut(
    df['Age'],
    bins=[0, 12, 50, 100],
    labels=['Child', 'Adult', 'Senior']
)
df[['Age', 'AgeGroup']]
df.groupby('AgeGroup')['Survived'].mean()

/tmp/ipykernel_186/3056760593.py:7: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('AgeGroup')['Survived'].mean()

AgeGroup
Child     0.333333
Adult     0.388889
Senior    0.250000
Name: Survived, dtype: float64

In [112]:
df.corr(numeric_only=True)['Survived'].sort_values(ascending=False)

Survived       1.000000
PassengerId    0.101527
Pclass         0.047723
Parch          0.019184
Age           -0.004273
Fare          -0.019917
SibSp         -0.038094
Name: Survived, dtype: float64

In [123]:
df["ALONE"] = (df["Parents"] == 0 ). astype(int)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Parents,ALONE
0,1,0,3,Passenger_1,male,22.6,3,1,TKT1000,242.58,B28,S,4,0
1,2,1,1,Passenger_2,female,18.9,4,3,TKT1001,222.11,NaN,C,7,0
2,3,1,1,Passenger_3,male,28.5,0,3,TKT1002,232.66,NaN,S,3,0
3,4,0,3,Passenger_4,female,15.5,0,2,TKT1003,248.78,C85,S,2,0
4,5,0,3,Passenger_5,male,22.2,4,3,TKT1004,51.73,B28,S,7,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,196,0,3,Passenger_196,male,39.7,0,3,TKT1195,50.20,NaN,C,3,0
196,197,1,3,Passenger_197,female,55.9,1,1,TKT1196,35.10,NaN,C,2,0
197,198,1,2,Passenger_198,male,45.8,0,0,TKT1197,162.74,NaN,S,0,1
198,199,1,3,Passenger_199,male,26.2,0,0,TKT1198,179.55,E46,S,0,1
199,200,1,3,Passenger_200,male,14.5,3,1,TKT1199,17.58,NaN,S,4,0

In [133]:
df["HasCabin"] = df["Cabin"].notnull().astype(int)

In [134]:
df.drop("Cabin", axis=1, inplace=True)

In [135]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,HasCabin
0,1,0,3,Passenger_1,male,22.6,3,1,TKT1000,242.58,S,1
1,2,1,1,Passenger_2,female,18.9,4,3,TKT1001,222.11,C,0
2,3,1,1,Passenger_3,male,28.5,0,3,TKT1002,232.66,S,0
3,4,0,3,Passenger_4,female,15.5,0,2,TKT1003,248.78,S,1
4,5,0,3,Passenger_5,male,22.2,4,3,TKT1004,51.73,S,1
...,...,...,...,...,...,...,...,...,...,...,...,...
195,196,0,3,Passenger_196,male,39.7,0,3,TKT1195,50.20,C,0
196,197,1,3,Passenger_197,female,55.9,1,1,TKT1196,35.10,C,0
197,198,1,2,Passenger_198,male,45.8,0,0,TKT1197,162.74,S,0
198,199,1,3,Passenger_199,male,26.2,0,0,TKT1198,179.55,S,1
199,200,1,3,Passenger_200,male,14.5,3,1,TKT1199,17.58,S,0